/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dnnUtil_dnnModel_DnnModel_W_Type */

#ifndef _Included_dnnUtil_dnnModel_DnnModel_W_Type
#define _Included_dnnUtil_dnnModel_DnnModel_W_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
