/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dnnUtil_dnnModel_DnnModel */

#ifndef _Included_dnnUtil_dnnModel_DnnModel
#define _Included_dnnUtil_dnnModel_DnnModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dnnUtil_dnnModel_DnnModel
 * Method:    jniCreateModel
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_dnnUtil_dnnModel_DnnModel_jniCreateModel
  (JNIEnv *, jobject);

/*
 * Class:     dnnUtil_dnnModel_DnnModel
 * Method:    jniUpdateModel
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_dnnUtil_dnnModel_DnnModel_jniUpdateModel
  (JNIEnv *, jobject);

/*
 * Class:     dnnUtil_dnnModel_DnnModel
 * Method:    jniLoadModel
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_dnnUtil_dnnModel_DnnModel_jniLoadModel
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     dnnUtil_dnnModel_DnnModel
 * Method:    jniTrainModel
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_dnnUtil_dnnModel_DnnModel_jniTrainModel
  (JNIEnv *, jobject);

/*
 * Class:     dnnUtil_dnnModel_DnnModel
 * Method:    jniLoadTrainingData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dnnUtil_dnnModel_DnnModel_jniLoadTrainingData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
